name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: PranavAD36
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23ff0000&color_dots=%23161b22,%23330000,%23660000,%23990000,%23ff0000

      - name: Push Snake Animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
